baseURL: https://santiagosotelo.netlify.app/
title: Santiago Sotelo
theme: hugo-theme-m10c
paginate: 8
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 2
    - identifier: about
      name: About
      url: /about/
      weight: 3
    - identifier: https://drive.google.com/file/d/1hMYSbxXtBUFn3BTshzL-grIYtCyySOi9/view?usp=sharing
      name: CV
      url: /cv.pdf/
      weight: 3      
params:
  author: Santiago Sotelo
  description: Sociología, análisis de datos, Black Mirror [?]
  avatar: https://lh3.googleusercontent.com/IJHCH-GVatSC1EFr8NqE9kcLofT8YbMi9f7UlVH_3CYm9QBguAU1aNLhQG8CSUnyXZ9CY1WM_6gKZLLfFtX_YsuqnlPtMQ5ZQED2BWHMB9sfGQfM2emIB9RKxvkgzpjel-mU60CVyh56p8g9hjaSzhLuU1IPulexVXy8Ichvt3_9hkXfW5mNLn_BkuPUMkP5tVSJXqV0inEfD8lGkOOthHsUAMKme74SBuL901Ewcct7J-8Qu4kNzUsXONmTakW3l3QP5Co8IPGMUmCeWXUnpF99wPnIBqfUTKVtZ-S1l34gZZPpIKoKsTkZn-HUWleepmhmBH42aGWNu-WdgxiMC7iLfT9UpTISAOUXnbGBQVenBqO1Wxsxj62uiyrhYN2By3x5X9Ri6SjM7AA505DMQ-VCwNTnda9ybeypSFGjKNG81XHwhUKuPq4bV1FKJ2qBytcvUQ9FSIa7KSmuvDYrgzYDr2I0pqkug2MliSZEfKprBn2UsNqtk78YcbBFXVOFqzZz8cUzEOLfryGW3my3sY1tqWqg5MXqJQX-4SKFccxdDQf6qKqPxyuD0SBJsYgoveDbaldW80GqRquhq4h99nbmTkx5iSnCMsCalN8Tcu7sFUOT37W6xBsMtmy3NZUDj47aOMk5kBkgf5GFxYVLueuvKeOzsKCGMYia8Vr8lQXkCygJzcFgCYHehzGvc8VHzVtJtjOrf-9bNTSLwNrjkxi6=s242-no?authuser=1
  menu_item_separator: ' - '
  social:
    - icon: github
      name: Github
      url: https://github.com/aito123
    - icon: linkedin
      name: Linkedin
      url: https://www.linkedin.com/in/santiago-sotelo-989574171

markup:
  goldmark:
    renderer:
      unsafe: true
