baseURL: https://santiagosotelo.netlify.app/
title: Santiago Sotelo
theme: hugo-theme-m10c
paginate: 8
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 2
    - identifier: about
      name: About
      url: /about/
      weight: 3
params:
  author: Santiago Sotelo
  description: Sociología, análisis de datos, Black Mirror [?]
  avatar: "C:/Users/Lenovo/Documents/mywebsite/resources/_gen/images/avatar.jpg"
  menu_item_separator: ' - '
  social:
    - icon: github
      name: Github
      url: https://github.com/aito123
    - icon: linkedin
      name: Linkedin
      url: https://www.linkedin.com/in/santiago-sotelo-989574171
